/* MATRIX SYNC — SERVICE WORKER
   Generated by build.sh from sw_template.js. 2026-09-05.49 is replaced at
   build time, which is also what makes the browser notice a new worker: a
   service worker is only re-installed when its BYTES change, so a version
   that never moved would leave every device on the first worker they ever saw.

   WHY THIS EXISTS
   iOS was already keeping its own copy of index.html — which is why the app
   opened in aeroplane mode on 5 Sep — but that is the browser being generous,
   not us being right. That cache can be evicted at any time: low storage, a
   long gap between uses, ordinary housekeeping. It would work almost always
   and then fail one morning for no reason anyone could see. This replaces
   "hope iOS kept a copy" with "we keep our own, deliberately".

   THE RULE THAT MATTERS MOST
   The document is fetched NETWORK-FIRST, not cache-first.

   Cache-first is the obvious way to build this and it would recreate a fault
   they have already suffered twice — Chris, 4 Sep: "both phone nor pc can
   complete the update". applyUpdate navigates to ?v=<new version>. A
   cache-first worker would answer that with the OLD page, the app would come
   back as the old build, read version.txt, see a newer number and offer the
   update again. For ever, on every device, with nothing on screen to say why.

   So: network first, with a short timeout, falling back to cache. Online the
   document is always fresh and the existing update flow is untouched. Offline
   the cached copy answers. The timeout matters on a factory floor — a weak
   signal must not make startup slower than it is today.

   version.txt is network-only for the same reason: it is the update check, and
   an update check answered from cache is not a check.

   THE ESCAPE HATCH
   A service worker that serves a broken build can brick the app on a device
   nobody can reach. Loading the app with ?sw=off unregisters this worker and
   clears its caches — see the registration block in index.html. Nothing here
   is worth losing a device over. */

const VERSION = "2026-09-05.49";
const CACHE = "matrix-sync-" + VERSION;

/* The runtime. Everything the app needs to start with no network at all.
   Relative paths throughout: this is served from /matrix-production/ on
   GitHub Pages and an absolute /vendor/react.js would 404 there. */
const SHELL = [
  "./",
  "./index.html",
  "./vendor/react.production.min.js",
  "./vendor/react-dom.production.min.js",
  "./vendor/supabase.js",
  "./manifest.webmanifest",
  "./apple-touch-icon.png",
  "./icon-192.png",
  "./favicon-32.png",
];

const DOC_TIMEOUT_MS = 2500;

self.addEventListener("install", (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    /* Added one at a time, not with addAll. addAll rejects the WHOLE install
       if any single file 404s — so one missing icon would mean no service
       worker at all, and no offline app, with nothing to say why. The shell
       files that matter are checked below; a missing icon is not worth
       failing over. */
    await Promise.all(SHELL.map(async (url) => {
      try {
        const res = await fetch(url, { cache: "reload" });
        if (res.ok) await cache.put(url, res.clone());
      } catch { /* offline at install time: the fetch handler will fill it in */ }
    }));
    // The app cannot start without these. If they are not cached there is no
    // point pretending this worker offers anything, so let install fail and
    // leave the device exactly as it was.
    const must = ["./index.html", "./vendor/react.production.min.js", "./vendor/react-dom.production.min.js"];
    for (const url of must) {
      if (!(await cache.match(url))) throw new Error("shell incomplete: " + url);
    }
    await self.skipWaiting();
  })());
});

self.addEventListener("activate", (event) => {
  event.waitUntil((async () => {
    for (const key of await caches.keys()) {
      if (key.startsWith("matrix-sync-") && key !== CACHE) await caches.delete(key);
    }
    await self.clients.claim();
  })());
});

self.addEventListener("message", (event) => {
  // Used by the ?sw=off escape hatch and by the Admin reset.
  if (event.data === "mx-unregister") {
    event.waitUntil((async () => {
      for (const key of await caches.keys()) {
        if (key.startsWith("matrix-sync-")) await caches.delete(key);
      }
      await self.registration.unregister();
    })());
  }
});

function isDoc(request) {
  return request.mode === "navigate"
    || (request.destination === "document")
    || /\/(index\.html)?(\?|$)/.test(new URL(request.url).pathname + new URL(request.url).search);
}

self.addEventListener("fetch", (event) => {
  const req = event.request;
  if (req.method !== "GET") return;                       // never touch a write
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;        // Supabase, CDNs: not ours

  // The update check must reach the server or it is not a check.
  if (url.pathname.endsWith("/version.txt")) return;

  if (isDoc(req)) {
    event.respondWith((async () => {
      try {
        const res = await Promise.race([
          fetch(req, { cache: "no-store" }),
          new Promise((_, reject) => setTimeout(() => reject(new Error("slow")), DOC_TIMEOUT_MS)),
        ]);
        if (res && res.ok) {
          const cache = await caches.open(CACHE);
          // Stored under the bare document key, so a later ?v=… navigation
          // offline still finds it.
          cache.put("./index.html", res.clone());
          return res;
        }
      } catch { /* offline, or slower than the floor should have to wait */ }
      const cached = await caches.match("./index.html", { ignoreSearch: true });
      return cached || Response.error();
    })());
    return;
  }

  // Everything else the app owns: serve from cache, refresh behind it.
  event.respondWith((async () => {
    const cache = await caches.open(CACHE);
    const cached = await cache.match(req, { ignoreSearch: false });
    const network = fetch(req).then((res) => {
      if (res && res.ok) cache.put(req, res.clone());
      return res;
    }).catch(() => null);
    return cached || (await network) || Response.error();
  })());
});
